export const CONNECTOR_DEVICE_RECOVERY_GRACE_SECONDS = 60;
export const CONNECTOR_DEVICE_RECOVERY_GRACE_MS =
  CONNECTOR_DEVICE_RECOVERY_GRACE_SECONDS * 1_000;
export const CONNECTOR_DEVICE_TOKEN_RATE_LIMIT_PER_MINUTE = 120;
